# frozen_string_literal: true

source 'https://rubygems.org' do
  gem 'pry', '~> 0.12.2'
  gem 'rspec', '~> 3.9'
  gem 'rubocop', require: false
  gem 'sqlite3', '~> 1.4', '>= 1.4.1'
  gem 'activemodel'
end
